config/routes.rb
Rails.application.routes.draw do

  resources :drops do
    resources :photos
  end

  root to: 'sessions#new'

  delete '/drops' => 'drops#destroy', as: 'received'

  delete '/sessions' => 'sessions#destroy', as: 'logout'
  resource :sessions, only: [:new, :create, :destroy]
  resource :user
  resources :users, only: [:index, :new, :create, :show]

end

app/models/drop.rb
class Drop < ActiveRecord::Base
	belongs_to :user
  belongs_to :receiver, class_name: "User", foreign_key: :recipient_id, inverse_of: :drops_waiting
	has_many :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :drop

  has_attached_file :image, :styles => { 
        :medium => "300x300>", 
        :thumb => "100x100>"
    },
    :default_url => "/images/:style/missing.png"

    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
	has_secure_password 
	has_many :drops
  has_many :drops_waiting, class_name: "Drop", foreign_key: :recipient_id, inverse_of: :receiver
	def full_name
		"#{first_name} #{last_name}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.where(id: session["user_id"]).first
  end
end

app/controllers/drops_controller.rb
class DropsController < ApplicationController
	def index
		@photos = Photo.where(recipient_id: current_user.id)
		@drops = Drop.where(recipient_id: current_user.id)
		@currentdrops = current_user.drops

	end

	def new
    	@drop = Drop.new
 	 end

	def create
	  #add the rest of the parameters for our working app LATER
	  drop = current_user.drops.new(params.require(:drop).permit(:spot, :description, :item, :latitude, :longitude, :landmark, :recipient_id, :title)) 
	  #which inputs will be allowed in the create controller
	  # drop.recipient_id = 
	  if drop.save
	    redirect_to drops_path(drop_created: 'true')
	  end
	end

	def show
		@drops = Drop.where(recipient_id: current_user.id)
		@drop = Drop.where(id: params[:id]).first
	end

	def destroy
		@drop = Drop.find(params[:id])
		@photo = @drop.photos
		@photo.destroy_all
		@drop.destroy
		redirect_to drops_path
	end
end

app/controllers/photos_controller.rb
 class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end
  def new
    @photo =Photo.new
    @drop = Drop.where(id:params[:drop_id]).first
  end
  def create
    @drop = Drop.where(id:params[:drop_id]).first
    # Find our user that we should attach to
    @photo = @drop.photos.new(photo_params)
    @photo.drop = @drop
    #or the standard create:
    # @photo = Photo.create(photo_params)
    if @photo.save
      redirect_to drop_path(@drop)
    else
      render 'new'
    end
  end

  def show

  end

  def photo_params
    params.require(:photo).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new #Any controller can create something from any other model!
    if params[:user_created] == 'true'
      # raise params.inspect
      @user_created_message = 'User successfully created!'
    end
  end


  def create
    # raise params.inspect
    #Find the user by email
    u = User.where(email: params[:user][:email]).first #in the params hash, you can pick up the user hash, 
    puts '======================================================'
    puts u
    puts '======================================================'
    #within which you can pick up the email key-value pair
    if u !=nil && u.authenticate(params[:user][:password]) #check that there is a user found and the password is correct
      session['user_id'] = u.id.to_s # hold on to idea that you are logged in, which is the session state. 
      #This is a special rails magic thing. This capitalized session has nothing to do with a model or 
      #even this controller which is called sessions. The Session in this case refers to something in Rails
      # that essentially is a cookie that will be passed around as long as the next page renders correctly
      redirect_to user_path(u) #should redirect to a dashboard. Just want to redirect to a page that we currently have
    end
  end

  def destroy
    session.destroy
    redirect_to new_sessions_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def index
    @user = User.all
  end

  def user_params
   params.require(:user).permit(:email, :password)
  end
  def new
    @user = User.new
  end

  def create
  	#add the rest of the parameters for our working app LATER
    user = User.new(params.require(:user).permit(:first_name, :last_name, :email, :password)) 
    #which inputs will be allowed in the create controller
    if user.save
      redirect_to new_sessions_path(user_created: 'true') #someone logs in here
    end
  end

  def show
    @user = User.find(session['user_id'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drops_helper.rb
module DropsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drops/index.html.erb
<%= link_to "Make a new drop", new_drop_path %>
</br>
<h1> Drops Received </h1>
<h2>
	<% current_user.drops_waiting.each do |d| %>
		<%= d.title	 %>
		</br>
		<%= d.description %>
		</br>
		<%= link_to "Add a landmark photograph", new_drop_photo_path(d) %>
	<% end %>
</h2>

<% @drops.each do |d| %>
	<%= button_to "received", d, method: :delete %>
	<br />
<%end %>

<!-- <#% @drops.photos.each do |p| %>
	<%#= image_tag p.image.url(:medium) %>
<%# end %> -->

<% @drops.each do |d| %>
	<% d.photos.each do |p| %>
		<%= image_tag p.image.url(:medium) %>
		<!-- Should not try to destroy photo right now, -->
		<!-- Will focus on destroying the entire drop, and then -->
		<!-- come back to this. -->
		<%#= button_to "delete", p, method: :delete %>
		<br />
	<% end %>
<% end %>

<h1> Drops Sent </h1>
<% @currentdrops.each do |c| %>
	Drop Title:
	<%= c.title %>
	</br>
	Drop Description:
	<%= c.description %>
	</br>
	<%= link_to "Add a landmark photo", new_drop_photo_path(c) %>
<% end %>

<% @currentdrops.each do |d| %>
	<%= button_to "delete", d, method: :delete %>
	<br />
<%end %>

<%# @currentdrops.each do |d| %>
	<%# d.photos.each do |p| %>
		<%#= image_tag p.image.url(:medium) %>
		<!-- Should not try to destroy photo right now, -->
		<!-- Will focus on destroying the entire drop, and then -->
		<!-- come back to this. -->
		<%#= button_to "delete", p, method: :delete %>
		<br />
	<%# end %>
<%# end %>


<%= render 'layouts/map' %>

app/views/drops/new.html.erb
<%= render 'layouts/new_drop_form' %>


<%= render 'layouts/map' %>

app/views/drops/show.html.erb
<% @drop.photos.each do |p| %>
	<%= image_tag p.image.url(:medium) %>
<% end %>
<% @drops.each do |d| %>
	<%= link_to "Add another Photo", new_drop_photo_path(d) %>
<% end %>

app/views/layouts/_new_drop_form.html.erb
<div id="new_drop_container">
	<%= bootstrap_form_for(@drop) do |f| %>
	  	<%= f.text_field :title %>
	  	<%= f.text_field :description %>
	  	<%= f.collection_select :recipient_id, User.all - [current_user], :id, :full_name %>
	  	<%= f.submit "Create Drop" %>
	<% end %>
</div>

app/views/layouts/_new_user_form.html.erb
<%= bootstrap_form_for(@user) do |f| %>
  	<%= f.text_field :first_name%>
  	<%= f.text_field :last_name %>
  	<%= f.text_field :email %>
  	<%= f.password_field :password %>
  	<%= f.submit "Sign Up" %>
<% end %>

app/views/layouts/_sign_in_form.html.erb
<li>
  <%= bootstrap_form_for @user, :url => { :controller => "sessions", :action => "create" } do |f| %>
      <%= f.text_field :email %>
      <%= f.password_field :password %>
      <%= f.submit "Sign in" %>
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <title>Hermes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>

      </button>
      <a class="navbar-brand" href="..">Hermes</a>
    </div>



      </form>
      <ul class="nav navbar-nav navbar-right">
      <!-- If we don't have a user signed in, we want to render the signup form and the login form -->
      <!-- Otherwise, we don't want to render the sign up form, and where it used to say login, we want to -->
      <!-- display the first and last name of the user currently signed in, and in the drop down form, we want a -->
      <!-- logout button a profile button and a drops button which destroys the current user session, takes the user -->
      <!-- to their profile where they can edit their settings and upload an avatar photo, and leads them to the page -->
      <!-- where they can view their current drops and make new drops, respectively -->
        <% if current_user == nil %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Sign Up
              <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
             <%= render partial: 'layouts/new_user_form' %>
            </ul>
            </a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Sign in
             <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <%= render partial: 'layouts/sign_in_form' %>
            </ul>
            </a>
          </li>
        <% else %> <!-- if our user is signed in, let's -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          <%= current_user.first_name %>
           <!-- display their name where the login button used to be -->
          <span class="caret"></span></a>
        <ul class ="dropdown-menu" role="menu"> <!-- and render the dropdown menu with buttons linking to the profile and linking to the user's drop page -->
            <li><a href="#">Profile</a></li>
            <li><a href="/drops">Drops</a></li>
            <li class="divider"></li>
            <li><%= button_to "Log out", sessions_path, method: :delete%></li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


  <%= yield %>



</body>
</html>

app/views/photos/index.html.erb
index.html.erb

app/views/photos/new.html.erb
<%= bootstrap_form_for [@drop,@photo] do |f| %>
  	<%= f.file_field :image%>
  	<%= f.submit "Upload" %>
<% end %>

app/views/users/index.html.erb
<h1> There's nothing here yet! </h1>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= form_for @user do |f|%>
	
    First name: <%= f.text_field :first_name %><br />
    Last name <%= f.text_field :last_name %> <br />
    E-mail: <%= f.text_field :email %><br />
    Password: <%= f.password_field :password %><br />
    Password confirmation: <%= f.password_field :password_confirmation %><br />

    <%=f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome to your user page <%= @user.email%> !</h1>

<p>You are now logged in.</p>
<p>E-mail:</p>


<%= @user.email %>

<%= link_to "Make a new drop", new_drop_path %></br>
<%= link_to "Go to your drops page", drops_path %>